version: "3.9"

services:
  app:
    container_name: homework_bot
    build:
      context: .
      dockerfile: Dockerfile
    command: python3.9 homework.py
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"